### ISSUE TITLE
Enhance schema to support gcode variants

### ISSUE THREAD

**Issue by zachallaun** [appliedengdesign/gcode-reference#1]
I think this is a very interesting project and I'd like to be able to contribute to it. However, all gcode is not made alike. I own a Brother and a Mazak machining center, and there are numerous MTB-specific G- and M- codes that I'd love to be able to contribute here, but it appears at the moment that the schema does not support "variants" of gcode.

As a quick, concrete example, M10 and M11 are [currently defined](https://github.com/appliedengdesign/gcode-reference/blob/main/src/json/mill/mcodes.json#L57) as brake enable/release. In Mazak EIA, M11 is going to unclamp the tool in your spindle 😅. Instead, you'd need to use M46 (unclamp 4th) and M47 (clamp 4th).

All the best,
Zach

**Comment by mikecentola** [comment]
@zachallaun You are correct. There should be a way we can have multiple variants and the code to load them would just have to reference which variant you'd want to pull in. I've been busy IRL with a new building we're moving into so I hope to get back to developing on this soon.

**Comment by mikecentola** [comment]
@zachallaun I'm going to work on some coding for this tonight. I'm going to start by adding a sub-type option to the reference allowing someone to call, for instance, ```const gref = new GReference(GRef.MachineTypes.Mill, SubTypes.Mazak);``` or ```SubTypes.Haas``` etc.

I'll figure out a coherent way to do it LOL

**Comment by tyeth** [comment]
Heya, any luck on this :) I want to add the snapmaker original (a restricted command set) and snapmaker 2.0 A350 which supports marlin 2.0 [https://snapmaker.github.io/Documentation/gcode/G000-G001](https://snapmaker.github.io/Documentation/gcode/G000-G001)

**Comment by mikecentola** [comment]
@tyeth sorry I've been super busy with my main job that I've neglected to work on these. Planning to get back to hit here shortly.

**Comment by tyeth** [comment]
I know how that goes, just finally taken a week off. 
No worries, low priority, fear not. Just seemed a good solution to the problem I had at the time

**Comment by mikecentola** [comment]
@zachallaun @tyeth - I just release v0.0.4 on here and npmjs. It support variants in all of the code. The variants don't need to contain the entire code library, only the ones that would change the main G or M codes. I tried to give an explanation of it in [CONTRIBUTING](https://github.com/appliedengdesign/gcode-reference/blob/main/CONTRIBUTING.md)

You can also take a look at the sample Mazak one I did here: [m.mazak.cncc.json](https://github.com/appliedengdesign/gcode-reference/blob/main/src/json/mill/variants/m.mazak.cncc.json)

Any help you guys want to start working on inside of the JSON files, feel free to create an issue for the one you'd be working on.

**Comment by tyeth** [comment]
@mikecentola while setting up a new duplicated milling file it told me the variant field in the mill\m.mazak.cncc.json example should be 3-8 _lowercase_ characters, the mazac starts capitol M in your example file. I'm assuming I have to use the example Snapmaker variants.ts string "snpmaker" instead of my original guess "Snapmaker". Thanks for this work :)

**Comment by mikecentola** [comment]
@tyeth  You are correct. It should be lower case `mazak` in the [`m.mazak.cncc.json`](https://github.com/appliedengdesign/gcode-reference/blob/main/src/json/mill/variants/m.mazak.cncc.json) file. I was trying to keep them short for file name length when I wrote the [CNC Codes JSON Schema](https://appliedengdesign.github.io/cnccodes-json-schema).
