### ISSUE TITLE
Feature Request: Optional removal of existing defined mcode/gcode entries for a Variant

### ISSUE THREAD

**Issue by tyeth** [appliedengdesign/gcode-reference#2]
Hi, I'm adding the Snapmaker 2.0 A350 and started with the additional Mcodes it supports for Milling + Lasering.
I started with the milling file and made a variant like the Mazak example, but I want to turn off the support for some (or all except 05 in this specific case) of the Mcodes that are not supported (m03-5 and M1010-11 are only ones [supported](https://snapmaker.github.io/Documentation/gcode/M003)). This isn't a problem for laser as currently there aren't the same default predefined Mcodes.
 Running the `npm run getCodes mill:mcode:snpmaker` on my [branch](https://github.com/tyeth/snapmaker2-gcode-reference/tree/snapmaker2-a350) gets all the default defined Mcodes and then merges my changes on top (makes sense), but I can't see how to turn off the other Mcodes.
Also on a tangent, but related, could be nice to show the next depth in output 
![image](https://user-images.githubusercontent.com/6692083/180461623-46b7b590-efaa-4eaa-aaa3-c0df27171cb2.png)

My variant looks like this currently 
![image](https://user-images.githubusercontent.com/6692083/180461996-cb2fb060-104b-428f-b046-ed5e0576a798.png)

**Comment by mikecentola** [comment]
@tyeth Should be an easy thing to do. I'll just have to update the schema to allow for another property.

Let's do it like this:
```json
"remove": [
    "M03",
    "M04",
    "M05
]

etc...

Then I can set the code to remove those matching keys when loading a variant.

**Comment by mikecentola** [comment]
@tyeth Ok I've updated the [CNC Codes JSON Schema](https://github.com/appliedengdesign/cnccodes-json-schema) to allow for the variant to be an object that carries the name and the "remove" array. You can update the code you're working on to be:

```json
"variant": {
    "name": "snpmaker",
    "remove": [
        "M01",
        "M02"
    ]
}
```

and so on...

I'm working on the other stuff on the dev branch right now.

**Comment by mikecentola** [comment]
Everything has been added to the dev branch. Will release v0.0.5 this weekend

**Comment by mikecentola** [comment]
Closing since v0.0.5 was just released
